//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fire_Emblem_Empires.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fire_Emblem_Empires.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9X11
        ///A1 3
        ///A2 3
        ///A3 3
        ///A4 3
        ///A5 3
        ///A6 3
        ///A7 3
        ///A8 2
        ///A9 2
        ///A10 2
        ///A11 1
        ///B1 3
        ///B2 3
        ///B3 3
        ///B4 1
        ///B5 1
        ///B6 3
        ///B7 0 0 4 R //17 17 4 9 7 0 0 // E
        ///B8 0 0 3 20 20 5 6 1 7 0 // E
        ///B9 1
        ///B10 1
        ///B11 0 0 2 23 23 7 5 7 0 0 // E
        ///C1 3
        ///C2 0
        ///C3 0
        ///C4 0
        ///C5 0 0 1 23 23 6 4 7 1 0 // E
        ///C6 0 0 0 20 20 6 8 5 0 0 // E
        ///C7 0
        ///C8 0 0 4 24 24 2 3 1 5 0 // E
        ///C9 3
        ///C10 1 0 3 16 16 8 6 7 5 0 // E
        ///C11 0
        ///D1 2
        ///D2 4
        ///D3 1
        ///D4 3
        ///D5 1
        ///D6 0
        ///D7 0 0 2 20 20 10 9 3 0 0 // E
        ///D8 0
        ///D9 3
        ///D10 3
        ///D11 0
        ///E1 2
        ///E2 2
        ///E3 3
        ///E4 1
        ///E5 1        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chapter1T1 {
            get {
                return ResourceManager.GetString("Chapter1T1", resourceCulture);
            }
        }
    }
}
